"use client";

import * as React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@workspace/ui/components/dialog";
import { Button } from "@workspace/ui/components/button";
import { Input } from "@workspace/ui/components/input";
import { Label } from "@workspace/ui/components/label";
import {
  Select,
  SelectTrigger,
  SelectContent,
  SelectItem,
  SelectValue,
} from "@workspace/ui/components/select";
import { Alert, AlertDescription } from "@workspace/ui/components/alert";
// removed cn; no longer needed after slug removal
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { createBrowserClient } from "@/utils/supabase/client";
import { useMutation } from "@tanstack/react-query";
import { schoolApi } from "@/entities/school/api/endpoints";

type InviteNewSchoolDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

export function InviteNewSchoolDialog({
  open,
  onOpenChange,
}: InviteNewSchoolDialogProps) {
  const [step, setStep] = React.useState(0);
  // no slug editing needed; slug is generated by the database
  const supabase = React.useMemo(() => createBrowserClient(), []);
  const [states, setStates] = React.useState<
    Array<{ id: string; code: string; name: string }>
  >([]);
  const [statesLoading, setStatesLoading] = React.useState<boolean>(false);
  const [statesError, setStatesError] = React.useState<string | null>(null);

  React.useEffect(() => {
    let mounted = true;
    async function loadStates() {
      setStatesLoading(true);
      setStatesError(null);
      const { data, error } = await supabase
        .from("states")
        .select("id, code, name")
        .order("name");
      if (!mounted) return;
      if (error) {
        setStatesError(error.message);
        setStates([]);
      } else {
        setStates(
          (data ?? []).filter(
            (s): s is { id: string; code: string; name: string } =>
              Boolean(s?.id && s?.code && s?.name)
          )
        );
      }
      setStatesLoading(false);
    }
    loadStates();
    return () => {
      mounted = false;
    };
  }, [supabase]);
  const levels = ["Primary", "Secondary", "Both"] as const;
  const sectors = ["Government", "Catholic", "Independent"] as const;
  const [confirmedReview, setConfirmedReview] = React.useState(false);

  const schema = z.object({
    name: z.string().min(1, "School name is required"),
    state: z.string().min(1, "State is required"),
    address: z.string().optional(),
    level: z.enum(levels, "Level is required"),
    sector: z.enum(sectors, "Sector is required"),
    email: z
      .string()
      .min(1, "Email is required")
      .email("Enter a valid email address"),
  });

  type FormValues = z.infer<typeof schema>;

  const form = useForm<FormValues>({
    resolver: zodResolver(schema as any),
    defaultValues: {
      name: "",
      state: "",
      address: "",
      level: undefined as unknown as FormValues["level"],
      sector: undefined as unknown as FormValues["sector"],
      email: "",
    },
    mode: "onChange",
  });

  const name = form.watch("name");
  const state = form.watch("state");

  // No slug generation/effect

  const steps = [
    {
      key: "details",
      title: "School details",
      content: (
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">School name</Label>
            <Input
              id="name"
              placeholder="e.g. Melbourne Grammar"
              {...form.register("name")}
            />
            {form.formState.errors.name && (
              <p className="text-xs text-destructive">
                {form.formState.errors.name.message}
              </p>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="address">Address (optional)</Label>
            <Input
              id="address"
              placeholder="Street, suburb, postcode"
              {...form.register("address")}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="state">State</Label>
            <Select
              value={form.watch("state")}
              onValueChange={(code) =>
                form.setValue("state", code, { shouldValidate: true })
              }
              disabled={statesLoading}
            >
              <SelectTrigger id="state">
                <SelectValue
                  placeholder={statesLoading ? "Loading..." : "Select state"}
                />
              </SelectTrigger>
              <SelectContent>
                {states.map((s) => (
                  <SelectItem key={s.id} value={s.code}>
                    {s.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {statesError && (
              <p className="text-xs text-destructive">{statesError}</p>
            )}
            {form.formState.errors.state && (
              <p className="text-xs text-destructive">
                {form.formState.errors.state.message}
              </p>
            )}
          </div>
        </div>
      ),
      validate: async () => {
        const results = await form.trigger(["name", "state"], {
          shouldFocus: true,
        });
        return results;
      },
    },
    {
      key: "classification",
      title: "Classification",
      content: (
        <div className="space-y-4">
          {/* Slug removed - handled by database */}
          <div className="space-y-2">
            <Label htmlFor="level">Level</Label>
            <Select
              value={form.watch("level") || undefined}
              onValueChange={(v) =>
                form.setValue("level", v as FormValues["level"], {
                  shouldValidate: true,
                })
              }
            >
              <SelectTrigger id="level">
                <SelectValue placeholder="Select level" />
              </SelectTrigger>
              <SelectContent>
                {levels.map((l) => (
                  <SelectItem key={l} value={l}>
                    {l}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {form.formState.errors.level?.message && (
              <p className="text-xs text-destructive">
                {form.formState.errors.level.message}
              </p>
            )}
          </div>
          <div className="space-y-2">
            <Label htmlFor="sector">Sector</Label>
            <Select
              value={form.watch("sector") || undefined}
              onValueChange={(v) =>
                form.setValue("sector", v as FormValues["sector"], {
                  shouldValidate: true,
                })
              }
            >
              <SelectTrigger id="sector">
                <SelectValue placeholder="Select sector" />
              </SelectTrigger>
              <SelectContent>
                {sectors.map((s) => (
                  <SelectItem key={s} value={s}>
                    {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {form.formState.errors.sector?.message && (
              <p className="text-xs text-destructive">
                {form.formState.errors.sector.message}
              </p>
            )}
          </div>
        </div>
      ),
      validate: async () => {
        const results = await form.trigger(["level", "sector"], {
          shouldFocus: true,
        });
        return results;
      },
    },
    {
      key: "contact",
      title: "Contact",
      content: (
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">School email address</Label>
            <Alert>
              <AlertDescription>
                This email should be a neutral email address that belongs to the
                school's domain, like 'info@school.edu.au'. This account will be
                the holder of the platform licence and is separate from the
                school-admin account of the school, which will assign classes
                and teachers.
              </AlertDescription>
            </Alert>
            <Input
              id="email"
              type="email"
              placeholder="e.g. info@school.edu.au"
              {...form.register("email")}
            />
            {form.formState.errors.email && (
              <p className="text-xs text-destructive">
                {form.formState.errors.email.message}
              </p>
            )}
          </div>
        </div>
      ),
      validate: async () => {
        const results = await form.trigger(["email"], { shouldFocus: true });
        return results;
      },
    },
    {
      key: "review",
      title: "Review",
      content: (
        <div className="space-y-4">
          <div className="space-y-1">
            <div className="text-sm text-muted-foreground">
              Please review the details before inviting.
            </div>
          </div>
          <div className="space-y-2 text-sm">
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground">School name</span>
              <span className="font-medium">{form.watch("name") || "—"}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground">Address</span>
              <span className="font-medium">
                {form.watch("address") || "—"}
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground">State</span>
              <span className="font-medium">
                {(() => {
                  const code = form.watch("state");
                  const found = states.find((s) => s.code === code);
                  return found ? `${found.name} (${found.code})` : code || "—";
                })()}
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground">Level</span>
              <span className="font-medium">{form.watch("level") || "—"}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground">Sector</span>
              <span className="font-medium">{form.watch("sector") || "—"}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground">School email</span>
              <span className="font-medium">{form.watch("email") || "—"}</span>
            </div>
          </div>

          <div className="flex items-start gap-2 pt-2">
            <input
              id="confirm"
              type="checkbox"
              className="mt-0.5"
              checked={confirmedReview}
              onChange={(e) => setConfirmedReview(e.target.checked)}
            />
            <label htmlFor="confirm" className="text-sm">
              All of these details are correct
            </label>
          </div>
        </div>
      ),
      validate: async () => {
        // No additional validation; relies on previous steps
        return true;
      },
    },
  ];

  const isFirst = step === 0;
  const isLast = step === steps.length - 1;

  // POST to /api/schools/invite using TanStack Query and API client
  const inviteMutation = useMutation({
    mutationFn: async (payload: any) => {
      const result = await schoolApi.post.inviteSchool(payload);
      if (result.error) {
        throw new Error(result.error.message || "Failed to invite school");
      }
      return result.data;
    },
  });

  async function goNext() {
    const ok = await steps[step]!.validate();
    if (!ok) return;
    if (!isLast) setStep((s) => s + 1);
    else handleSubmit();
  }

  function goBack() {
    if (!isFirst) setStep((s) => s - 1);
  }

  async function handleSubmit() {
    const values = form.getValues();
    const payload = {
      // Send through the dialog values; server currently just logs them
      name: values.name,
      state: values.state,
      address: values.address,
      level: values.level,
      sector: values.sector,
      email: values.email,
    };
    try {
      await inviteMutation.mutateAsync(payload);
      onOpenChange(false);
      setStep(0);
      form.reset();
    } catch (e) {
      // Error is displayed below via inviteMutation.error
    }
  }

  React.useEffect(() => {
    if (!open) return;
    // Do not reset on open/close to preserve selections during dialog lifetime
    // We only reset on successful submit in handleSubmit
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl max-h-[70vh] h-full">
        <DialogHeader>
          <DialogTitle>Invite new school</DialogTitle>
          <DialogDescription>
            Provide a few details to invite a school to BullyProof.
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-full">
          <div className="hidden md:flex items-center justify-center">
            <div className="w-full h-full rounded-md bg-muted/60 flex items-center justify-center p-6 min-h-[260px]">
              <div className="text-center space-y-2">
                <div className="text-5xl">🏫</div>
                <p className="text-sm text-muted-foreground">
                  Invite a new school
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-4 w-full">
            <ol className="flex items-center gap-2" aria-label="Progress">
              {steps.map((s, idx) => (
                <li key={s.key} className="flex items-center gap-2">
                  <div
                    className={
                      "size-2 rounded-full transition-colors " +
                      (idx <= step ? "bg-primary" : "bg-muted-foreground/30")
                    }
                    aria-hidden
                  />
                  {idx < steps.length - 1 && (
                    <div className="h-px w-6 bg-border" aria-hidden />
                  )}
                </li>
              ))}
            </ol>

            <form
              id="invite-school-form"
              onSubmit={(e) => {
                e.preventDefault();
                void goNext();
              }}
              className="space-y-4"
            >
              <div>{steps[step]!.content}</div>
              {inviteMutation.error && (
                <Alert>
                  <AlertDescription>
                    {(inviteMutation.error as Error).message}
                  </AlertDescription>
                </Alert>
              )}
            </form>
          </div>
        </div>

        <DialogFooter>
          <div className="flex w-full items-center justify-between">
            <Button
              type="button"
              variant="ghost"
              onClick={() => onOpenChange(false)}
            >
              Cancel
            </Button>
            <div className="flex items-center gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={goBack}
                disabled={isFirst || inviteMutation.isPending}
              >
                Back
              </Button>
              <Button
                type="submit"
                form="invite-school-form"
                disabled={
                  (isLast && !confirmedReview) || inviteMutation.isPending
                }
              >
                {inviteMutation.isPending
                  ? "Submitting..."
                  : isLast
                    ? "Invite"
                    : "Continue"}
              </Button>
            </div>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
