import { nextJsConfig } from "@workspace/eslint-config/next-js";

/** @type {import("eslint").Linter.Config} */
export default [
  ...nextJsConfig,
  {
    ignores: [
      // Generated by drizzle introspect
      "drizzle/schema.ts",
      "drizzle/relations.ts",
      // Vendored minified pdf.js worker
      "public/pdf.worker.min.mjs",
    ],
  },
];
