import { nextJsConfig } from "@workspace/eslint-config/next-js"

/** @type {import("eslint").Linter.Config} */
export default [
  {
    ignores: [
      ".cache/**",
      // Generated by `pnpm gen-types` — never hand-edited, so not linted.
      "types/supabase.ts",
      // Vendored reference snippets kept for copy-paste, not shipped.
      "components/reference/**",
      "dist/**",
    ],
  },
  ...nextJsConfig,
  {
    // Node CLI scripts and long-running bots run outside the Next bundle.
    files: [
      "scripts/**",
      "discord-bot/**",
      "cs2-gc-bot/**",
      "steam-friends-bot/**",
    ],
    languageOptions: {
      globals: {
        process: "readonly",
        console: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        crypto: "readonly",
      },
    },
  },
]
